config/routes.rb
Rails.application.routes.draw do
  resources :events, :athletes_events_meets
  resources :athletes_meets, only: [:update]

  get 'meets/:meet_id/athletes/:athlete_id/events', to: 'athletes_events_meets#index', as: :meet_athlete_events
  get 'athletes/:athlete_id/events/:event_id/meets', to: 'athletes_events_meets#index', as: :athlete_event_meets

  resources :athletes do
    resources :events
  end

  resources :meets do
    resources :athletes, shallow: true
  end

  root 'meets#index'

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :athletes_meets
  has_many :meets, through: :athletes_meets
  has_many :athletes_events_meets
  has_many :events, through: :athletes_events_meets

  def self.default_order
    order :class_level, :birth_date

  end

  def personal_best(event)
    AthletesEventsMeet.by_athlete_event(self, event).map(&:score).max
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    return unless birth_date
    now = Time.now.utc.to_date
    now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
  end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athlete_collection = AthleteCollection.new params
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:first_name, :last_name, :age_level, :class_level, :birth_date, :start_date)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for(@athlete, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @athlete.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h4>

      <ul>
      <% @athlete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age_level, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :age_level, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :class_level, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :class_level, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birth_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :birth_date, start_year: 2000, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :start_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<div class="page-header">
  <%= link_to athletes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @athlete, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing athlete</h1>
</div>

<%= render 'form' %>

app/views/athletes/index.html.erb
<div class="page-header">
  <%= link_to new_athlete_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Athlete
  <% end %>

  <h1><%= meet_name %> Athletes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Birth date</th>
        <th>Age</th>
        <th>Age level</th>
        <th>Class level</th>
        <th>Start date</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @athlete_collection.athletes) do |athlete| %>
        <td><%= athlete.first_name %></td>
        <td>
          <% if @athlete_collection.meet %>
            <%= link_to athlete.last_name, meet_athlete_events_path(@athlete_collection.meet, athlete) %>
          <% else %>
            <%= athlete.last_name %>
          <% end %>
        </td>
        <td><%= athlete.birth_date %></td>
        <td><%= athlete.age %></td>
        <td><%= athlete.age_level %></td>
        <td><%= athlete.class_level %></td>
        <td><%= athlete.start_date %></td>
        <td><%= link_to 'Show', athlete %></td>
        <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
        <td><%= link_to 'Destroy', athlete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/athletes/new.html.erb
<div class="page-header">
  <%= link_to athletes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New athlete</h1>
</div>

<%= render 'form' %>

app/views/athletes/show.html.erb
<div class="page-header">
  <%= link_to athletes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_athlete_path(@athlete), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show athlete</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @athlete.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @athlete.last_name %></dd>

  <dt>Age level:</dt>
  <dd><%= @athlete.age_level %></dd>

  <dt>Class level:</dt>
  <dd><%= @athlete.class_level %></dd>

  <dt>Birth date:</dt>
  <dd><%= @athlete.birth_date %></dd>

  <dt>Start date:</dt>
  <dd><%= @athlete.start_date %></dd>

</dl>