config/routes.rb
Rails.application.routes.draw do
  resources :events, :athletes_events_meets
  resources :athletes_meets, only: [:update]

  get 'meets/:meet_id/athletes/:athlete_id/events', to: 'athletes_events_meets#index', as: :meet_athlete_events
  get 'athletes/:athlete_id/events/:event_id/meets', to: 'athletes_events_meets#index', as: :athlete_event_meets

  resources :athletes do
    resources :events
  end

  resources :meets do
    resources :athletes, shallow: true
  end

  root 'meets#index'

end

app/models/meet.rb
class Meet < ActiveRecord::Base
  has_many :athletes_meets
  has_many :athletes, through: :athletes_meets
  has_many :athletes_events_meets
  has_many :events, through: :athletes_events_meets

  after_save :initialize_events

  DEFAULT_EVENT_NAMES = ["Floor", "Pommel Horse", "Rings", "Vault", "Parallel Bars", "High Bars"]

  def self.default_order
    order :meet_date
  end

  private

  def initialize_events
    events = Event.where("name in (?)", DEFAULT_EVENT_NAMES)
    athletes.each do |athlete|
      events.each do |event|
        AthletesEventsMeet.where( { athlete_id: athlete.id,
                                     event_id: event.id,
                                     meet_id: id } ).first_or_create
      end
    end
  end
end

app/views/tournaments/_add_athletes.html.erb
<table class="table table-hover">
  <thead>
    <th>Add</th>
    <th>Athlete Name</th>
    <th>Class Level</th>
    <th>Age Level</th>
    <th>Age</th>
  </thead>
  <tbody>
    <% athletes.each do |athlete| %>
      <tr>
        <td>
          <%= check_box_tag "tournament[athlete_ids][]", athlete.id, tournament.athletes.include?(athlete) %>
        </td>
        <td> <%= athlete.full_name %> </td>
        <td> <%= athlete.class_level %> </td>
        <td> <%= athlete.age_level %> </td>
        <td> <%= athlete.age %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tournaments/_form.html.erb
<%= form_for(@tournament, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @tournament.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h4>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :venue, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :venue, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :event_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :event_date, :class => "form-control" %>
    </div>
  </div>
  <h4> Add Athletes </h4>

  <%= render partial: 'add_athletes', locals: { tournament: @tournament, athletes: Athlete.all } %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<div class="page-header">
  <%= link_to tournaments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @tournament, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing tournament</h1>
</div>

<%= render 'form' %>

app/views/tournaments/new.html.erb
<div class="page-header">
  <%= link_to tournaments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New tournament</h1>
</div>

<%= render 'form' %>