config/routes.rb
Rails.application.routes.draw do
  resources :events, :athletes_events_meets
  resources :athletes_meets, only: [:update]

  get 'meets/:meet_id/athletes/:athlete_id/events', to: 'athletes_events_meets#index', as: :meet_athlete_events
  get 'athletes/:athlete_id/events/:event_id/meets', to: 'athletes_events_meets#index', as: :athlete_event_meets

  resources :athletes do
    resources :events
  end

  resources :meets do
    resources :athletes, shallow: true
  end

  root 'meets#index'

end

app/models/meet.rb
class Meet < ActiveRecord::Base
  has_many :athletes_meets
  has_many :athletes, through: :athletes_meets
  has_many :athletes_events_meets
  has_many :events, through: :athletes_events_meets

  after_save :initialize_events

  DEFAULT_EVENT_NAMES = ["Floor", "Pommel Horse", "Rings", "Vault", "Parallel Bars", "High Bars"]

  def self.default_order
    order :meet_date
  end

  private

  def initialize_events
    events = Event.where("name in (?)", DEFAULT_EVENT_NAMES)
    athletes.each do |athlete|
      events.each do |event|
        AthletesEventsMeet.where( { athlete_id: athlete.id,
                                     event_id: event.id,
                                     meet_id: id } ).first_or_create
      end
    end
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: [:show, :edit, :update, :destroy]

  # GET /meets
  # GET /meets.json
  def index
    @meets = Meet.default_order
  end

  # GET /meets/1
  # GET /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets
  # POST /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: 'Meet was successfully created.' }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1
  # PATCH/PUT /meets/1.json
  def update
    params[:meet][:athlete_ids] ||= []
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: 'Meet was successfully updated.' }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1
  # DELETE /meets/1.json
  def destroy
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: 'Meet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meet_params
      params.require(:meet).permit(:name, :venue, :address, :city, :state,
                                   :zip, :meet_date, { athlete_ids: [] })
    end
end

app/helpers/meet_helper.rb
module MeetHelper
end

app/views/meets/_add_athletes.html.erb
<table class="table table-hover">
  <thead>
    <th>Add</th>
    <th>Athlete Name</th>
    <th>Class Level</th>
    <th>Age Level</th>
    <th>Age</th>
  </thead>
  <tbody>
    <% athletes.each do |athlete| %>
      <tr>
        <td>
          <%= check_box_tag "meet[athlete_ids][]", athlete.id, meet.athletes.include?(athlete) %>
        </td>
        <td> <%= athlete.full_name %> </td>
        <td> <%= athlete.class_level %> </td>
        <td> <%= athlete.age_level %> </td>
        <td> <%= athlete.age %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meets/_form.html.erb
<%= form_for(@meet, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @meet.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@meet.errors.count, "error") %> prohibited this meet from being saved:</h4>

      <ul>
      <% @meet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :venue, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :venue, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :meet_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :meet_date, :class => "form-control" %>
    </div>
  </div>
  <h4> Add Athletes </h4>

   <%= render partial: 'add_athletes', locals: { meet: @meet, athletes: Athlete.all } %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/meets/edit.html.erb
<div class="page-header">
  <%= link_to meets_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @meet, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Meet</h1>
</div>

<%= render 'form' %>

app/views/meets/index.html.erb
<div class="page-header">
  <%= link_to new_meet_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Meet
  <% end %>
  <h1>Meets</h1>
</div>

<% if false && @meet_collection.athlete && @meet_collection.event %>
  <%= render partail: 'athlete_event_scores', locals: { athlete: @meet_collection.athlete,
                                                        event: @meet_collection.event } %>
<% else %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Venue</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th>Event date</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%= content_tag_for(:tr, @meets) do |meet| %>
              <td><%= link_to meet.name, meet_athletes_path(meet) %></td>
              <td><%= meet.venue %></td>
              <td><%= meet.address %></td>
              <td><%= meet.city %></td>
              <td><%= meet.state %></td>
              <td><%= meet.zip %></td>
              <td><%= meet.meet_date %></td>
              <td><%= link_to 'Show', meet %></td>
              <td><%= link_to 'Edit', edit_meet_path(meet) %></td>
              <td><%= link_to 'Destroy', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/meets/new.html.erb
<div class="page-header">
  <%= link_to meets_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Meet</h1>
</div>

<%= render 'form' %>

app/views/meets/show.html.erb
<div class="page-header">
  <%= link_to meets_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_meet_path(@meet), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show meet</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @meet.name %></dd>

  <dt>Venue:</dt>
  <dd><%= @meet.venue %></dd>

  <dt>Address:</dt>
  <dd><%= @meet.address %></dd>

  <dt>City:</dt>
  <dd><%= @meet.city %></dd>

  <dt>State:</dt>
  <dd><%= @meet.state %></dd>

  <dt>Zip:</dt>
  <dd><%= @meet.zip %></dd>

  <dt>Meet date:</dt>
  <dd><%= @meet.meet_date %></dd>

</dl>

<% unless @meet.athletes.empty? %>
  <h4>Athletes</h4>
  <table class="table">
    <thead>
      <td>Athlete Name</td>
      <td>Class Level</td>
      <td>Age Level</td>
      <td>Age</td>
    </thead>
    <tbody>
      <% @meet.athletes.each do |athlete| %>
        <tr>
          <td><%= athlete.full_name %> </td>
          <td><%= athlete.class_level %> </td>
          <td><%= athlete.age_level %> </td>
          <td><%= athlete.age %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>